# Generated by Django 5.2.5 on 2025-08-12 05:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('organization_url', models.URLField(verbose_name='Orga_URL')),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('post_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Die PLZ muss aus 5 Ziffern bestehen.', regex='^\\d{5}$')], verbose_name='Postleitzahl')),
            ],
        ),
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('event_url', models.URLField(verbose_name='Event_URL')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='eventapp.organizationsmodel')),
            ],
        ),
    ]
