# Generated by Django 5.2.5 on 2025-09-06 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('event_url', models.URLField(blank=True, default='http://127.0.0.1:8000/', verbose_name='Event-URL')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ort')),
                ('target_group', models.CharField(blank=True, max_length=200, verbose_name='Zielgruppe')),
                ('start_date', models.DateTimeField(verbose_name='Startdatum')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Enddatum')),
                ('is_public', models.BooleanField(default=True, verbose_name='Öffentlich')),
                ('registration_required', models.BooleanField(default=False, verbose_name='Registrierung erforderlich')),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Optional: Maximale Anzahl an Teilnehmern für dieses Event', null=True, verbose_name='Maximale Teilnehmerzahl')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='authapp.organization', verbose_name='Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nachname')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail-Adresse')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Anmeldedatum')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='eventapp.eventmodel')),
            ],
            options={
                'unique_together': {('event', 'email')},
            },
        ),
    ]
