# Generated by Django 5.2.5 on 2025-08-16 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_organizations_delete_veranstaltung_delete_verein_and_more'),
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='authapp.organizations'),
        ),
        migrations.DeleteModel(
            name='OrganizationsModel',
        ),
    ]
