# Generated by Django 5.2.5 on 2025-08-29 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_organizations_delete_veranstaltung_delete_verein_and_more'),
        ('eventapp', '0002_alter_eventmodel_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='event_url',
            field=models.URLField(blank=True, null=True, verbose_name='Event_URL'),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='authapp.organizations'),
        ),
    ]
