# Generated by Django 5.2.5 on 2025-08-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_alter_eventmodel_event_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='event_url',
            field=models.URLField(blank=True, default='http://127.0.0.1:8000/', verbose_name='Event_URL'),
        ),
    ]
