# Generated by Django 5.2.5 on 2025-08-29 14:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_alter_eventmodel_event_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Erstellt am'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='end_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Enddatum'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Öffentlich'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ort'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Startdatum'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='target_group',
            field=models.CharField(blank=True, max_length=200, verbose_name='Zielgruppe'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Geändert am'),
        ),
    ]
