# Generated by Django 5.2.5 on 2025-08-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_eventmodel_created_at_eventmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enddatum'),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='start_date',
            field=models.DateTimeField(verbose_name='Startdatum'),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Geändert am'),
        ),
    ]
