# Generated by Django 5.2.5 on 2025-08-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0006_alter_eventmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Erstellt am'),
        ),
    ]
