# Generated by Django 5.2.5 on 2025-08-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0007_alter_eventmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Optional: Maximale Anzahl an Teilnehmern für dieses Event', null=True, verbose_name='Maximale Teilnehmerzahl'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='registration_required',
            field=models.BooleanField(default=False, verbose_name='Registrierung erforderlich'),
        ),
    ]
