# Generated by Django 5.2.5 on 2025-08-31 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_organization_city'),
        ('eventapp', '0008_eventmodel_max_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='event_url',
            field=models.URLField(blank=True, default='http://127.0.0.1:8000/', verbose_name='Event-URL'),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='authapp.organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titel'),
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nachname')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail-Adresse')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Anmeldedatum')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='eventapp.eventmodel')),
            ],
            options={
                'unique_together': {('event', 'email')},
            },
        ),
    ]
