# Generated by Django 5.2.5 on 2025-08-16 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('organization_url', models.URLField(verbose_name='Orga_URL')),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('post_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Die PLZ muss aus 5 Ziffern bestehen.', regex='^\\d{5}$')], verbose_name='Postleitzahl')),
                ('authenticity_checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Veranstaltung',
        ),
        migrations.DeleteModel(
            name='Verein',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vereine',
            field=models.ManyToManyField(blank=True, related_name='mitglieder', to='authapp.organizations'),
        ),
    ]
