# Generated by Django 5.2.5 on 2025-08-29 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_organizations_delete_veranstaltung_delete_verein_and_more'),
        ('eventapp', '0004_alter_eventmodel_event_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organizations',
            new_name='Organization',
        ),
    ]
