# Generated by Django 5.2.5 on 2025-08-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_rename_organizations_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
