# Generated by Django 5.2.4 on 2025-07-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anbieter',
            name='allow_edit_by_ansprechperson',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anbieter',
            name='beschreibung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anbieter',
            name='ort',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anbieter',
            name='plz',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='anbieter',
            name='straße',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
